project:
  name: s
  language: JavaScript
checks:
  JavaScript:
    eslint: true
    prettier: true
autofix:
  enabled: true
ignore:
  - node_modules
  - dist
  - build
  - coverage
  - .git
  - packages.json
  - package.json
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - bun.lockb
  - "*.min.js"
